os.environ: 0
/home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ta/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ta/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ta/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ta/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ta/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ta/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
1.14.0
WARNING:tensorflow:From run.py:20: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

ok
dataset information: nodes:811076, n_sequence:120, n_steps:17 
===================configuration===================
dropout prob :  0.001
l2 0.05
learning rate :  0.005
emb_learning_rate :  0.005
observation hour [7,19]
observation threshold :  7200
prediction time :  86400
cascade length [10,100]
model save at : ../model_save/deephawkes/weibo/
===================configuration===================
---------***---------
Number: 29669, Max: 15.089202175838759 and Min: 0.0 label Value in Train
NUmber: 6358, Max: 14.264955662710035 and Min: 0.0 label Value in Test
NUmber: 6358, Max: 13.518038379578142 and Min: 0.0 label Value in Valid
---------***---------
29669 6358 6358
WARNING:tensorflow:From run.py:166: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From run.py:166: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2021-07-14 23:25:38.120413: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-07-14 23:25:38.126098: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-07-14 23:25:39.011829: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a4225742a0 executing computations on platform CUDA. Devices:
2021-07-14 23:25:39.011915: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): TITAN RTX, Compute Capability 7.5
2021-07-14 23:25:39.036420: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3499910000 Hz
2021-07-14 23:25:39.038349: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a4227a6140 executing computations on platform Host. Devices:
2021-07-14 23:25:39.038430: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2021-07-14 23:25:39.041567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: TITAN RTX major: 7 minor: 5 memoryClockRate(GHz): 1.77
pciBusID: 0000:1a:00.0
2021-07-14 23:25:39.041842: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/bin
2021-07-14 23:25:39.041978: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/bin
2021-07-14 23:25:39.042098: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/bin
2021-07-14 23:25:39.042212: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/bin
2021-07-14 23:25:39.042326: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/bin
2021-07-14 23:25:39.042464: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/bin
2021-07-14 23:25:39.049414: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-07-14 23:25:39.049495: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2021-07-14 23:25:39.049533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-14 23:25:39.049565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2021-07-14 23:25:39.049580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:37: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:38: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:130: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:148: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:160: GRUCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.GRUCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:196: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:Large dropout rate: 0.999 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.
WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:209: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
WARNING:tensorflow:From /home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py:564: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py:574: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method GRUCell.call of <tensorflow.python.ops.rnn_cell_impl.GRUCell object at 0x7f71e337f748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:From /home/ta/yh/open-cas/models/DeepHawkes/utils/model.py:85: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

Total_parameters:40579055
WARNING:tensorflow:From /home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/ta/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2021-07-14 23:25:41.320922: W tensorflow/core/common_runtime/colocation_graph.cc:1016] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:1' assigned_device_name_='' resource_device_name_='/device:GPU:1' supported_device_types_=[CPU] possible_devices_=[]
Fill: CPU XLA_CPU XLA_GPU 
Assign: CPU 
Identity: CPU XLA_CPU XLA_GPU 
VariableV2: CPU 
Mul: CPU XLA_CPU XLA_GPU 
Add: CPU XLA_CPU XLA_GPU 
Sub: CPU XLA_CPU XLA_GPU 
RandomUniform: CPU XLA_CPU XLA_GPU 
ApplyAdam: CPU 
Const: CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Initializer/random_uniform/shape (Const) 
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Initializer/random_uniform/min (Const) 
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Initializer/random_uniform/max (Const) 
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Initializer/random_uniform/RandomUniform (RandomUniform) 
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Initializer/random_uniform/sub (Sub) 
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Initializer/random_uniform/mul (Mul) 
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Initializer/random_uniform (Add) 
  deephawkes/RNN/rnn/gru_cell/gates/kernel (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam/Initializer/zeros/shape_as_tensor (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam/Initializer/zeros/Const (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam/Initializer/zeros (Fill) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam/read (Identity) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam_1/Initializer/zeros/shape_as_tensor (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam_1/Initializer/zeros/Const (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam_1/Initializer/zeros (Fill) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam_1 (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam_1/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/kernel/Adam_1/read (Identity) /device:GPU:1
  Adam/update_deephawkes/RNN/rnn/gru_cell/gates/kernel/ApplyAdam (ApplyAdam) /device:GPU:1

2021-07-14 23:25:41.321201: W tensorflow/core/common_runtime/colocation_graph.cc:1016] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:1' assigned_device_name_='' resource_device_name_='/device:GPU:1' supported_device_types_=[CPU] possible_devices_=[]
Assign: CPU 
Identity: CPU XLA_CPU XLA_GPU 
VariableV2: CPU 
ApplyAdam: CPU 
Const: CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  deephawkes/RNN/rnn/gru_cell/gates/bias/Initializer/Const (Const) 
  deephawkes/RNN/rnn/gru_cell/gates/bias (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam/Initializer/zeros (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam/read (Identity) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam_1/Initializer/zeros (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam_1 (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam_1/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/gates/bias/Adam_1/read (Identity) /device:GPU:1
  Adam/update_deephawkes/RNN/rnn/gru_cell/gates/bias/ApplyAdam (ApplyAdam) /device:GPU:1

2021-07-14 23:25:41.321363: W tensorflow/core/common_runtime/colocation_graph.cc:1016] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:1' assigned_device_name_='' resource_device_name_='/device:GPU:1' supported_device_types_=[CPU] possible_devices_=[]
Fill: CPU XLA_CPU XLA_GPU 
Assign: CPU 
Identity: CPU XLA_CPU XLA_GPU 
VariableV2: CPU 
Mul: CPU XLA_CPU XLA_GPU 
Add: CPU XLA_CPU XLA_GPU 
Sub: CPU XLA_CPU XLA_GPU 
RandomUniform: CPU XLA_CPU XLA_GPU 
ApplyAdam: CPU 
Const: CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Initializer/random_uniform/shape (Const) 
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Initializer/random_uniform/min (Const) 
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Initializer/random_uniform/max (Const) 
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Initializer/random_uniform/RandomUniform (RandomUniform) 
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Initializer/random_uniform/sub (Sub) 
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Initializer/random_uniform/mul (Mul) 
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Initializer/random_uniform (Add) 
  deephawkes/RNN/rnn/gru_cell/candidate/kernel (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam/Initializer/zeros/shape_as_tensor (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam/Initializer/zeros/Const (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam/Initializer/zeros (Fill) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam/read (Identity) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam_1/Initializer/zeros/shape_as_tensor (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam_1/Initializer/zeros/Const (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam_1/Initializer/zeros (Fill) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam_1 (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam_1/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/kernel/Adam_1/read (Identity) /device:GPU:1
  Adam/update_deephawkes/RNN/rnn/gru_cell/candidate/kernel/ApplyAdam (ApplyAdam) /device:GPU:1

2021-07-14 23:25:41.321504: W tensorflow/core/common_runtime/colocation_graph.cc:1016] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:1' assigned_device_name_='' resource_device_name_='/device:GPU:1' supported_device_types_=[CPU] possible_devices_=[]
Mul: CPU XLA_CPU XLA_GPU 
Assign: CPU 
Identity: CPU XLA_CPU XLA_GPU 
VariableV2: CPU 
ApplyAdam: CPU 
Const: CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Initializer/zeros (Const) 
  deephawkes/RNN/rnn/gru_cell/candidate/bias (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Assign (Assign) /device:GPU:1
  beta1_power/initial_value (Const) /device:GPU:1
  beta1_power (VariableV2) /device:GPU:1
  beta1_power/Assign (Assign) /device:GPU:1
  beta1_power/read (Identity) /device:GPU:1
  beta2_power/initial_value (Const) /device:GPU:1
  beta2_power (VariableV2) /device:GPU:1
  beta2_power/Assign (Assign) /device:GPU:1
  beta2_power/read (Identity) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam/Initializer/zeros (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam/read (Identity) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam_1/Initializer/zeros (Const) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam_1 (VariableV2) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam_1/Assign (Assign) /device:GPU:1
  deephawkes/RNN/rnn/gru_cell/candidate/bias/Adam_1/read (Identity) /device:GPU:1
  Adam/update_deephawkes/RNN/rnn/gru_cell/candidate/bias/ApplyAdam (ApplyAdam) /device:GPU:1
  Adam/mul (Mul) /device:GPU:1
  Adam/Assign (Assign) /device:GPU:1
  Adam/mul_1 (Mul) /device:GPU:1
  Adam/Assign_1 (Assign) /device:GPU:1

2021-07-14 23:25:42.080582: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:From run.py:187: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver in inish one epoch, time248.035603046417 train mseloss : 2.7320224200503924
lambda1 [-0.    0.03  0.05  0.08  0.11  0.15]
#0, Training Loss= 2.74829, Valid Loss= 2.62963, Valid median Loss= 0.80888, Best Valid Loss= 2.62963, Test Loss= 2.66845, Test median  Loss= 0.80342, Best Test Loss= 2.668  inish one epoch, time807.97158360481 train mseloss : 2.190729992195924
lambda1 [-0.    0.01  0.05  0.07  0.1   0.17]
#1, Training Loss= 2.19196, Valid Loss= 2.12453, Valid median Loss= 0.60445, Best Valid Loss= 2.12453, Test Loss= 2.12931, Test median  Loss= 0.58428, Best Test Loss= 2.129  inish one epoch, time1403.029389619827 train mseloss : 2.1514297074920283
lambda1 [-0.   -0.01  0.04  0.07  0.13  0.19]
#2, Training Loss= 2.15559, Valid Loss= 2.06501, Valid median Loss= 0.62413, Best Valid Loss= 2.06501, Test Loss= 2.12523, Test median  Loss= 0.63737, Best Test Loss= 2.1252  inish one epoch, time1999.5268893241882 rain mseloss : 2.2170198786698903
lambda1 [-0.   -0.    0.05  0.07  0.15  0.21]
#3, Training Loss= 2.21135, Valid Loss= 2.16713, Valid median Loss= 0.59869, Best Valid Loss= 2.06501, Test Loss= 2.16084, Test median  Loss= 0.59437, Best Test Loss= 2.12523                                                       inish one epoch, time2594.2014009952545 train mseloss : 2.198834189737115
lambda1 [-0.   -0.    0.02  0.08  0.16  0.23]
#4, Training Loss= 2.19782, Valid Loss= 2.13617, Valid median Loss= 0.65817, Best Valid Loss= 2.06501, Test Loss= 2.13755, Test median  Loss= 0.64520, Best Test Loss= 2.12523                                                        inish one epoch, time3188.817803144455 train mseloss : 2.2099746168879317
lambda1 [-0.   -0.01  0.06  0.1   0.16  0.26]
#5, Training Loss= 2.21270, Valid Loss= 2.14525, Valid median Loss= 0.61287, Best Valid Loss= 2.06501, Test Loss= 2.16968, Test median  Loss= 0.60052, Best Test Loss= 2.12523                             finish one epoch, time3779.8137819767 train mseloss : 2.1226593895490105
lambda1 [-0.    0.    0.03  0.09  0.17  0.24]
#6, Training Loss= 2.12891, Valid Loss= 2.06680, Valid median Loss= 0.58728, Best Valid Loss= 2.06501, Test Loss= 2.08469, Test median  Loss= 0.56766, Best Test Loss= 2.08469                                                                                  finish one epoch, time4378.714322805405 train mseloss : 2.1313591960386593
lambda1 [-0.   -0.01  0.03  0.09  0.16  0.26]
#7, Training Loss= 2.13461, Valid Loss= 2.06818, Valid median Loss= 0.61817, Best Valid Loss= 2.06501, Test Loss= 2.09912, Test median  Loss= 0.61496, Best Test Loss= 2.08469                                                                                    finish one epoch, time4981.078882932663 train mseloss : 2.186231528676743
lambda1 [1.55e-05 9.65e-04 4.24e-02 9.84e-02 1.78e-01 2.69e-01]
#8, Training Loss= 2.18542, Valid Loss= 2.10963, Valid median Loss= 0.67883, Best Valid Loss= 2.06501, Test Loss= 2.14671, Test median  Loss= 0.67785, Best Test Loss= 2.08469               inish one epoch, time5584.000234365463 train mseloss : 2.1382144108550585
lambda1 [-0.   -0.01  0.06  0.1   0.18  0.28]
#9, Training Loss= 2.13582, Valid Loss= 2.08362, Valid median Loss= 0.59013, Best Valid Loss= 2.06501, Test Loss= 2.09613, Test median  Loss= 0.58032, Best Test Loss= 2.08469   inish one epoch, time6185.800981521606 train mseloss : 2.1136629786835264
lambda1 [-0.   -0.    0.03  0.11  0.19  0.29]
#10, Training Loss= 2.11281, Valid Loss= 2.04079, Valid median Loss= 0.63849, Best Valid Loss= 2.04079, Test Loss= 2.07476, Test median  Loss= 0.62089, Best Test Loss= 2.07476  inish one epoch, time6790.451032876968 train mseloss : 2.1681859592098895
lambda1 [-0.01 -0.    0.04  0.1   0.18  0.29]
#11, Training Loss= 2.17320, Valid Loss= 2.12332, Valid median Loss= 0.58811, Best Valid Loss= 2.04079, Test Loss= 2.11924, Test median  Loss= 0.57533, Best Test Loss= 2.07476  inish one epoch, time7399.802276611328 train mseloss : 2.1754622897080638
lambda1 [-0.01  0.01  0.05  0.11  0.21  0.29]
#12, Training Loss= 2.17616, Valid Loss= 2.09080, Valid median Loss= 0.63041, Best Valid Loss= 2.04079, Test Loss= 2.12724, Test median  Loss= 0.61319, Best Test Loss= 2.07476  inish one epoch, time8007.8350484371185 train mseloss : 2.192520796812669
lambda1 [-0.   -0.    0.04  0.11  0.2   0.31]
#13, Training Loss= 2.19219, Valid Loss= 2.13333, Valid median Loss= 0.60070, Best Valid Loss= 2.04079, Test Loss= 2.15527, Test median  Loss= 0.59396, Best Test Loss= 2.07476  inish one epoch, time8611.768481492996 train mseloss : 2.118506715929171
lambda1 [-0.   -0.    0.04  0.1   0.21  0.3 ]
#14, Training Loss= 2.11533, Valid Loss= 2.07079, Valid median Loss= 0.60092, Best Valid Loss= 2.04079, Test Loss= 2.07640, Test median  Loss= 0.58387, Best Test Loss= 2.07476  inish one epoch, time9214.407007455826 train mseloss : 2.2038670566607386
lambda1 [-0.    0.05  0.02  0.11  0.23  0.35]
#15, Training Loss= 2.20253, Valid Loss= 2.12497, Valid median Loss= 0.60002, Best Valid Loss= 2.04079, Test Loss= 2.13992, Test median  Loss= 0.58954, Best Test Loss= 2.07476   inish one epoch, time9818.71015882492 train mseloss : 2.133439280525187
lambda1 [-0.   -0.01  0.04  0.11  0.25  0.33]
#16, Training Loss= 2.13773, Valid Loss= 2.09037, Valid median Loss= 0.58151, Best Valid Loss= 2.04079, Test Loss= 2.10298, Test median  Loss= 0.57501, Best Test Loss= 2.07476   inish one epoch, time10429.580216407776 train mseloss : 2.125858996152501
lambda1 [-0.   -0.01  0.04  0.12  0.24  0.33]
#17, Training Loss= 2.12989, Valid Loss= 2.07843, Valid median Loss= 0.64488, Best Valid Loss= 2.04079, Test Loss= 2.09507, Test median  Loss= 0.63472, Best Test Loss= 2.07476 inish one epoch, time11044.046397209167 train mseloss : 2.1793305164029486
lambda1 [-0.01 -0.01  0.04  0.13  0.24  0.33]
#18, Training Loss= 2.18043, Valid Loss= 2.12574, Valid median Loss= 0.58043, Best Valid Loss= 2.04079, Test Loss= 2.13824, Test median  Loss= 0.56479, Best Test Loss= 2.07476 inish one epoch, time11656.844730377197 train mseloss : 2.1553731667577396
lambda1 [-0.01  0.01  0.05  0.11  0.23  0.34]
#19, Training Loss= 2.14922, Valid Loss= 2.07681, Valid median Loss= 0.61006, Best Valid Loss= 2.04079, Test Loss= 2.10927, Test median  Loss= 0.58903, Best Test Loss= 2.07476 inish one epoch, time12269.506056547165 train mseloss : 2.1680256652536114
lambda1 [-0.   -0.01  0.03  0.12  0.24  0.35]
#20, Training Loss= 2.17569, Valid Loss= 2.12115, Valid median Loss= 0.63171, Best Valid Loss= 2.04079, Test Loss= 2.15386, Test median  Loss= 0.59118, Best Test Loss= 2.07476                     640128it [3:32:25, 111.24it/s]                           Finished!
----------------------------------------------------------------
Time: 12745.83381652832
Valid Loss: 2.0407867
Test Loss: 2.0747614
